# Generated by Django 3.0.8 on 2020-07-08 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='название аллергена')),
            ],
            options={
                'verbose_name': 'аллерген',
                'verbose_name_plural': 'аллергены',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='название категории')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='название блюда')),
                ('image', models.ImageField(upload_to='menu_items', verbose_name='изображение блюда')),
                ('price', models.PositiveIntegerField(verbose_name='цена блюда')),
                ('calories', models.PositiveIntegerField(verbose_name='пищевая ценность')),
                ('allergens', models.ManyToManyField(related_name='menu_items', to='restaurant.Allergen', verbose_name='аллергены')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='restaurant.Category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'блюдо',
                'verbose_name_plural': 'блюда',
            },
        ),
    ]
